apiVersion: networking.istio.io/v1beta1
kind: VirtualService
...
metadata:
  name: cmpt756s1
spec:
  host: cmpt756s1
  subsets:
  - name: v1
    labels:
      version: v1
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percentage:
          value: 40
    route: 
    - destination: 
        host: cmpt756s1
        subset: v1
  - route:
    - destination: 
        host: cmpt756s1
        subset: v1   
